name: simple pipeline

on:
    push:
      branches:
        - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
      MAPBOX: ${{ secrets.MAPBOX }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm installbe
        run: npm install
        working-directory: backend
      - name: npm install fe
        run: npm install
        working-directory: ./frontend/my-app
      - name: npm lint
        run: npm run lint
        working-directory: backend
      - name: npm build
        run: npm run build:ui
        working-directory: backend
      - name: tsc
        run: npm run tsc
        working-directory: backend
      - name: test backend
        run: npm run test
        working-directory: backend
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
          working-directory: backend
      - name: deploy
        if: ${{ github.event_name == 'push' }} && contains(toJson(github.event.commits.*.message), '#skip') === false
        uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "obscure-retreat-23913"
          heroku_email: "mikkosakarikivisto@gmail.com"
          remote_branch: master
          healthcheck: "https://obscure-retreat-23913.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          appdir: "backend"
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: failure slack
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: success slack
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: author,commit,took # selectable (default: repo,message)
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `A new version deployed to https://obscure-retreat-23913.herokuapp.com/ (${process.env.AS_COMMIT})\nBy ${process.env.AS_AUTHOR} Build took ${process.env.AS_TOOK}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}