name: simple pipeline

on:
    push:
      branches:
        - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
      MAPBOX: ${{ secrets.MAPBOX }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm installbe
        run: npm install
        working-directory: backend
      - name: npm install fe
        run: npm install
        working-directory: ./frontend/my-app
      - name: npm lint
        run: npm run lint
        working-directory: backend
      - name: npm build
        run: npm run build:ui
        working-directory: backend
      - name: test backend
        run: npm run test
        working-directory: backend
