name: simple pipeline

on:
    push:
      branches:
        - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
        working-directory: backend
      - name: npm lint
        run: npm run lint
        working-directory: backend
      - name: npm build
        run: npm run build
        working-directory: frontend/myapp
      - name: test backend
        run: npm run test
        working-directory: backend
